apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "data-monitors.fullname" . }}-montecarlo-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  backendType: systemManager
  data:
    - key: /dps/montecarlo/api/id
      name: montecarlo_api_id
    - key: /dps/montecarlo/api/token
      name: montecarlo_api_token
