{{ if .Values.isLocal }}
apiVersion: 'v1'
kind: Secret
metadata:
  name: pg-localdb-secrets
  namespace: dps
type: kubernetes.io/basic-auth
data:
  host: "cG9zdGdyZXNxbC1sb2NhbGRiLmRwcy5zdmMuY2x1c3Rlci5sb2NhbA==" #postgresql-localdb.dps.svc.cluster.local (base 64)
  port: "NzY1NA==" # 7654 (base 64)
  username: "bG9jYWxwZw==" #localpg (base 64)
  password: "bG9jYWxwZw==" #localpg (base 64)
  database: "YWR0aHJpdmU=" # adthrive (base 64)
{{ end }}