dpsAirflow:
  executeMarmaladeJob: false

airflow:
  ingress:
    web:
      enabled: true
      host: airflow-dps.stage.cafemedia.com
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  extraEnv: |-
    - name: "AIRFLOW_VAR_ENV"
      value: "stage"
    - name: "AIRFLOW_VAR_AWS_ACCOUNT"
      value: "673670291312"
    - name: "DD_AGENT_HOST"
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: AIRFLOW__METRICS__STATSD_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
