_template: connection

resource_name: application_account

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: application_account
    namespace: public
