_template: connection

resource_name: publisher_application_vertical

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: publisher_application_vertical
    namespace: public
