_template: connection

resource_name: site_post_url_change

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: site_post_url_change
    namespace: public
