_template: connection

resource_name: site_video_ad_player

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: site_video_ad_player
    namespace: public
