_template: connection

resource_name: site_rpm_input_before

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: site_rpm_input_before
    namespace: public
