_template: connection

resource_name: site_data_source

source: adthrive_postgres_looker_replica
destination: snowflake_airbyte
status: active
streams:
  - name: site_data_source
    namespace: public
