_template: connection

resource_name: slickstream-mongodb-c03-navsites

source: slickstream_mongodb_c03
destination: slickstream-s3-landing-zone
status: active
namespace_format: c03/
streams:
  - name: navsites
    namespace: guild-server
    destination_sync_mode: append
