_template: connection

resource_name: slickstream-mongodb-c06-navsites

source: slickstream_mongodb_c06
destination: slickstream-s3-landing-zone
status: active
namespace_format: c06/
streams:
  - name: navsites
    namespace: guild-server
    destination_sync_mode: append
