_template: connection

resource_name: slickstream-mongodb-c07-navsites

source: slickstream_mongodb_c07
destination: slickstream-s3-landing-zone
status: active
namespace_format: c07/
streams:
  - name: navsites
    namespace: guild-server
    destination_sync_mode: append
