_template: connection

resource_name: slickstream-mongodb-c12-navsites

source: slickstream_mongodb_c12
destination: slickstream-s3-landing-zone
status: active
namespace_format: c12/
streams:
  - name: navsites
    namespace: guild-server
    destination_sync_mode: append
