_template: mongodb

resource_name: slickstream-mongodb-cluster-c11

user: ${SLICKSTREAM_MONGODB_USERNAME}
database: guild-server
password: ${SLICKSTREAM_MONGODB_PASSWORD}
auth_source: admin
tls: false
host: ${SLICKSTREAM_MONGODB_URL_C11}
port: ${SLICKSTREAM_MONGODB_PORT_C11}
instance: standalone
