apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-registry-helper
  namespace: dps
spec:
  schedule: "0-59/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false  
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: sa-registry-secret-cronjob
          containers:
          - name: ecr-registry-helper
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
              - |-
                set -e
                ECR_PASSWORD=$(aws ecr get-login-password --profile saml --region us-east-1)
                kubectl delete secret --ignore-not-found registry-secret-dev -n dps
                kubectl create secret docker-registry registry-secret-dev \
                --docker-server=312505582686.dkr.ecr.us-east-1.amazonaws.com \
                --docker-username=AWS \
                --docker-password=$ECR_PASSWORD \
                --namespace=dps
                echo "Secret was successfully updated at $(date)"
            volumeMounts:
            - name: aws-credentials
              mountPath: /home/user/.aws
          volumes:
          - name: aws-credentials
            hostPath: 
              path: /root/.aws
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-registry-secret-cronjob
  namespace: dps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dps
  name: role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["registry-secret-dev"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registry-cronjob-role-binding
  namespace: dps
subjects:
- kind: ServiceAccount
  name: sa-registry-secret-cronjob
  namespace: dps
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""