env:
  AWS_SDK_LOAD_CONFIG: 1
  AWS_SHARED_CREDENTIALS_FILE: /home/node/.aws/credentials
  AWS_CONFIG_FILE: /home/node/.aws/credentials
  AWS_PROFILE: saml
  AWS_REGION: us-east-1
extraVolumes:
  - name: aws-credentials
    hostPath:
      path: /root/.aws
extraVolumeMounts:
  - name: aws-credentials
    mountPath: /home/node/.aws