kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dps
nodes:
- role: control-plane
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
    - hostPath: {{ aws_hostPath }} 
      containerPath: /root/.aws/
    - hostPath: {{ dags_hostPath }}
      containerPath: /root/dags
    - hostPath: {{ airflow_logs_hostPath }}
      containerPath: /root/airflow-logs
    - hostPath: {{ airbyte_hostPath }}
      containerPath: /root/airbyte
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP