{{ if .Values.isLocal }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dps-platform-airflow.fullname" . }}-dags-remote-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "dps-platform-airflow.fullname" . }}-dags-local-test
  resources:
    requests:
      storage: 1Gi
{{ else if .Values.dpsAirflow.enableDagsEfsPV }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dps-platform-airflow.fullname" . }}-dags-remote-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "dps-platform-airflow.fullname" . }}-dags-efs
  resources:
    requests:
      storage: 5Gi
{{ end }}