apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hyak-repo-keys-public
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: /dps/key/hyak-repo/public
      name: id_rsa.pub
