apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-custom-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
spec:
  backendType: systemManager
  data:
    - key: /dps/airflow/user/password
      name: airflow_user_password
    - key: /dps/airflow/webserver/key
      name: webserver-secret-key
    - key: /dps/airflow/fernet/key
      name: fernet-key # name must match airflow chart
    - key: /dps/airflow/redis/password
      name: password # name must match airflow chart
    - key: /dps/airflow/broker/url
      name: connection