apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-metadata-connection-secret
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
spec:
  backendType: systemManager
  data:
    - key: /dps/airflow/db/airflow-db-rds-credentials
      name: connection
