apiVersion: v2
name: dps-platform-airbyte
description: Umbrella Helm Chart to Deploy Hyak Airbyte
type: application
version: 1.0.0
appVersion: 0.41.0

dependencies:
  - name: airbyte
    repository: https://chartmuseum.production.cafemedia.com
    version: 0.43.22
    condition: airbyte.enabled
