apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "airbyte-umbrella.fullname" . }}-airbyte-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
spec:
  backendType: systemManager
  data:
    {{ if .Values.isLocal }}
    - key: /dps/airbyte/user/access_key
      name: airbyte_user_access_key
    - key: /dps/airbyte/user/secret_key
      name: airbte_user_secret_key
    {{ else }}
    - key: /dps/airbyte/db/airbyte-db-2-rds-credentials-username
      name: DATABASE_USER
    - key: /dps/airbyte/db/airbyte-db-2-rds-credentials-password
      name: DATABASE_PASSWORD
    {{ end }}
    - key: /dps/airbyte/logs/access_key
      name: logs_access_key
    - key: /dps/airbyte/logs/secret_key
      name: logs_secret_key
    - key: /dps/airbyte/ui/password
      name: ui_password
    - key: /dps/airbyte/auth/basic
      name: auth
    - key: /dps/db/postgres/airbyte-service-user-password
      name: postgres_airbyte_service_user_password
  template:
    stringData:
      {{ if .Values.isLocal }}
      DATABASE_USER: airbyte
      DATABASE_PASSWORD: airbyte
      {{ end }}
      STATE_STORAGE_MINIO_ACCESS_KEY: "minio"
      STATE_STORAGE_MINIO_SECRET_ACCESS_KEY: "minio123"
