apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "airbyte-umbrella.fullname" . }}-postgres-secrets
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: all.db.postgres.host
      name: db.host
    - key: all.db.postgres.database
      name: db.database
    - key: all.db.postgres.master-user
      name: db.master-user
    - key: all.db.postgres.master-password
      name: db.master-password
