apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "airbyte-umbrella.fullname" . }}-salesforce-secrets
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: /dps/airbyte/salesforce/client-id
      name: client-id
    - key: /dps/airbyte/salesforce/client-secret
      name: client-secret
    - key: /dps/airbyte/salesforce/refresh-token
      name: refresh-token
