apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "airbyte-umbrella.fullname" . }}-slickstream-mongodb-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
spec:
  backendType: systemManager
  data:
    - key: /dps/airbyte/connections/slickstream/mongodb/password
      name: password
    - key: /dps/airbyte/connections/slickstream/mongodb/username
      name: username
