# External Secret
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: diffbot-keys
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: aud.external.api.diffbot
      name: diffbot-api-key
