# External Secret
# Creates and syncronizes a Kubernetes secret using a backend storage source
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: gam-keys-airflow
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: /dps/key/extractor/gam-application-credentials
      name: api-credentials