# External Secret
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: openai-keys
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: aud.external.api.openai
      name: openai-key
