{{ if .Values.isLocal }}
# External Secret
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: serpapi-keys
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: aud.external.api.serpapi
      name: serpapi-key
{{ end }}