# External Secret
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: target-keys-airflow
  namespace: dps
spec:
  backendType: systemManager
  data:
    - key: /dps/key/extractor/target-api-key
      name: target-api-key
    - key: /dps/key/extractor/target-api-user
      name: target-api-user