apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-monitors.fullname" . }}-files-configmap
data:
{{ range $path, $_ := .Files.Glob "monitor-configurations/**.yaml" }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{ end }}
