montecarlo:
  json_schema:
  - table: raw:airbyte._airbyte_raw_publisher_application
    name: Publisher Application JSON Schema Monitor
    timestamp_field: _airbyte_emitted_at
    where_condition: _airbyte_data = {}
    lookback_days: 1
    aggregation_time_interval: day
    schedule:
      type: fixed
      interval_minutes: 720
      start_time: '2023-05-22T19:56:27.920000+00:00'
      timezone: UTC
    description: Check for empty JSON object in RAW airbyte publisher application
    notes: Runbook https://cafemedia.atlassian.net/wiki/spaces/DPS/pages/3031924774/Airbyte+Empty+JSON+Object+Runbook
    labels:
    - DPS
    notify_rule_run_failure: true
    field: _airbyte_data