montecarlo:
  custom_sql:
    - sql: |
        WITH hours AS (
          SELECT DISTINCT (date || ' ' || hour || ':00Z')::DATETIME as hour
          FROM analytics.triplelift.vw_publisher_network
          WHERE date >= dateadd('day', -1, CURRENT_DATE)
        ),
        most_recent AS (
          SELECT MIN(DATEDIFF('hours', hour, CURRENT_TIMESTAMP(0))) as most_recent FROM hours
        )
        SELECT most_recent FROM most_recent;
      query_result_type: SINGLE_NUMERIC
      name: Alert-TripleLift-PublisherNetwork-Data Availability
      description: TripleLift PublisherNetwork most recent data availability
      notes: |
        This query checks for gaps between hours in the last 48 hours on the TRIPLELIFT.VW_PUBLISHER_NETWORK view.
        Get a list of distinct hours and verify that the difference between them in order is exactly 1. Otherwise, alert.
        Also ensure that the most recent date is at least yesterday.
        Most recent data is more than 15 hours old
        https://cafemedia.atlassian.net/wiki/spaces/DPS/pages/1559167071/TripleLift#Alert-TripleLift-PublisherNetwork-Data-Availability%3A
      comparisons:
        - type: threshold
          operator: GT
          threshold_value: 15
      schedule:
        type: fixed
        start_time: "2022-10-12T05:30:00"
        interval_minutes: 60
      labels:
        - DPS
