name: Test Resuable Extract Action

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy"
        default: "dev"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: check out repository
      uses: actions/checkout@v2
    - name: test
      run: |
        echo "Current environment is: ${{ inputs.environment }}"
        echo "Repo: $GITHUB_REPOSITORY"
        echo "Actor: $GITHUB_ACTOR"
