name: Test Resuable Extract Action

on:
  push:
    tags:
      - "v*.*.*-*.*"

jobs:
  extract:
    uses: ./.github/workflows/resuable-extract-environment-from-tag.yaml

  test:
    needs: [extract]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: test
      run: |
        echo "Current environment is: ${{needs.extract.outputs.result}}"
        echo "Repo: $GITHUB_ACTION_REPOSITORY"
        echo "Actor: $GITHUB_ACTOR"
